### ISSUE TITLE
API

### ISSUE THREAD

**Issue by chuchischef** [gfroerli/web#24]
Gibt's bei euch eine öffentliche API für die Sensoren?

**Comment by rnestler** [comment]
> Gibt's bei euch eine öffentliche API für die Sensoren?

Gibt es, die ist aber noch in Entwicklung: https://github.com/coredump-ch/water-sensor-api. Die API wird sich also noch jederzeit ändern können.

**Comment by chuchischef** [comment]
Super. Kann ich dafür einen Token bekommen?
Oder besser direkt da nachfragen?

**Comment by dbrgn** [comment]
@chuchischef was möchtest du denn damit genau bauen?

bevor wir tokens aushändigen, sollte eigentlich die API stabil sein. zudem müssen wir zuerst diskutieren, unter welcher lizenz wir die daten freigeben können :slightly_smiling_face:

**Comment by rnestler** [comment]
Du kannst dich auch via IRC oder so bei uns melden: https://www.coredump.ch/kontakt/. Klappt evt. besser als mit GitHub kommentaren :smiley:
