### ISSUE TITLE
Migrate API to new domain

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/web#37]
Use api.gfrör.li instead of the old Coredump domain.

Refs #33

**Comment by dbrgn** [comment]
```
danilo@c3po:~$ dig +short api.gfrör.li
danilo@c3po:~$
```

...no 🙂

To ensure compatibility, we'd need to think how we can handle the migration.

**Comment by rnestler** [comment]
> To ensure compatibility, we'd need to think how we can handle the migration.

Have both point to the same API server for some time? Then temporary redirect, then permanent redirect, then remove the old entry.

**Comment by dbrgn** [comment]
Does Rails use some kind of domain validation, where the valid domains need to be added to the config?

I'll set up the new domain, then we'll see 🙂

**Comment by dbrgn** [comment]
Seems to work!

- Old: https://watertemp-api.coredump.ch/
- New: https://api.gfrör.li/

I'll try to update the relay to the new domain as well.

**Comment by dbrgn** [comment]
@rnestler https://git.coredump.ch/infrastructure/server/-/merge_requests/112

**Comment by rnestler** [comment]
> Does Rails use some kind of domain validation, where the valid domains need to be added to the config?

Actually yes, but maybe we deactivated it?

**Comment by dbrgn** [comment]
> Actually yes, but maybe we deactivated it?

I don't know anything about Rails, so you'll have to tell me 😂

**Comment by dbrgn** [comment]
Website is now updated. Still TO DO:

- Update Android app: https://github.com/gfroerli/app-android/issues/60
- Update iOS app: https://github.com/gfroerli/app-iOS/issues/1

(And then, add a permanent redirect from the old to the new domain and look at logs. Once no requests come in for a few weeks to the old domain, we can stop serving it.)
