### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/web#41]
https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

Potentially we need to wait for a few dependencies.

**Comment by rnestler** [comment]
I tried running elm-upgrade, but some of our dependencies need fixing:
```
WARNING! 5 of your dependencies have not yet been upgraded to
support Elm 0.19.
  - https://github.com/elm-community/maybe-extra
  - https://github.com/elm-lang/navigation
  - https://github.com/mgold/elm-date-format
  - https://github.com/rtfeldman/elm-css
  - https://github.com/terezka/line-charts
```

elm-lang/navigation is no problem, it just got replaced by elm/browser, but line-charts is probably hard to fix.

**Comment by dbrgn** [comment]
Yeah, we definitely need to wait for line-charts.

I hope the project is not dead, since two typo-PRs I made a while ago haven't been merged: https://github.com/terezka/line-charts/pulls

In any case, I'd wait a month or two for the dependencies to catch up.

**Comment by dbrgn** [comment]
Done in #44

**Comment by rnestler** [comment]
> Yeah, we definitely need to wait for line-charts.

Did you ditch line-charts?

**Comment by dbrgn** [comment]
No, it was upgraded in the meantime.
