### ISSUE TITLE
Link to iOS app

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/web#68]
...as soon as it's published.

**Comment by Makram95** [comment]
[https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html](url)

Smart-linking zur App, wenn man via Safari für iOS die Website besucht, wäre vielleicht auch noch eine Überlegung wert :)

**Comment by dbrgn** [comment]
Fixed in #78!
